extends Camera3D
class_name BaseCamera

## Base camera script with zone system and priority support
## Override update_camera() in child classes to implement different camera behaviors

@export var follow_target: Node3D
@export var enabled: bool = true

# Camera parameters (set by MultimediaZone when auto-generated)
var is_prebuilt: bool = true # Will be set to false when auto-generated by MultimediaZone
var active_zones: Array[MultimediaZone] = []
var current_zone: MultimediaZone = null
var initial_position: Vector3
var initial_forward: Vector3

func _ready():
	# Only auto-assign player target for auto-generated cameras
	if not follow_target and not is_prebuilt:
		follow_target = GameManager.player
	
	# Store initial transform for look-only mode
	initial_position = global_position
	initial_forward = - global_transform.basis.z.normalized()
	
	# Register with CameraManager
	if CameraManager:
		CameraManager.register_camera(self)
	
	# Register with GameManager if this is the main camera
	if name == "MainCamera" or get_parent().name == "MainCamera":
		GameManager.main_camera = self

func _physics_process(delta):
	if not enabled:
		return
	
	# Update current zone based on priority
	_update_active_zone()
	
	# Call the camera update logic (override in children)
	update_camera(delta)

## Override this method in child classes to implement camera behavior
func update_camera(delta: float) -> void:
	pass

## Update which zone is active based on priority
func _update_active_zone() -> void:
	var previous_zone = current_zone
	
	if active_zones.is_empty():
		current_zone = null
		return
	
	# Sort by priority (highest first)
	active_zones.sort_custom(func(a, b): return a.prio > b.prio)
	current_zone = active_zones[0]
	
	# If zone changed, make this camera current
	if current_zone != previous_zone and current_zone != null:
		print("[BaseCamera] Zone changed to: ", current_zone.name, " - making camera current")
		make_current()

## Called by MultimediaZone when player enters
func register_zone(zone: MultimediaZone) -> void:
	if zone not in active_zones:
		active_zones.append(zone)
		print("[BaseCamera] Registered zone: ", zone.name, " (priority: ", zone.prio, ")")

## Called by MultimediaZone when player exits
func unregister_zone(zone: MultimediaZone) -> void:
	active_zones.erase(zone)
	print("[BaseCamera] Unregistered zone: ", zone.name)

## Get the current zone's target position (useful for zones with custom targets)
func get_zone_target() -> Node3D:
	if current_zone and current_zone.custom_target:
		return current_zone.custom_target
	return follow_target

## Get target position with optional sprite offset
func get_target_position(target: Node3D) -> Vector3:
	if not target:
		return Vector3.ZERO
	var target_pos = target.global_position
	if target.has_node("Sprite3D"):
		target_pos = target.get_node("Sprite3D").global_position
	return target_pos
